import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/server";
import {
  listShippingPolicies,
  getShippingPolicy,
  createShippingPolicy,
  updateShippingPolicy,
} from "@/lib/vtex/shipping-policies";
import {
  listFreightTables,
  getFreightRates,
  setFreightRates,
  deleteFreightRates,
} from "@/lib/vtex/freight-rates";
import { listTradePolicies, checkShippingSetup } from "@/lib/vtex/shipping-setup";
import { safe, safeNoArgs } from "../utils";

/** One row of a shipping rate table, as a person would state it. */
const freightRate = z.object({
  postalCodeStart: z.string().describe('As written, e.g. "01000" — padded to 8 digits internally'),
  postalCodeEnd: z.string(),
  price: z
    .number()
    .describe("Fixed shipping cost in the account currency, e.g. 5 or 5.9 — NOT cents"),
  deliveryDays: z.number().int().min(0).optional().describe("Default 1"),
  weightStart: z.number().optional().describe("Default 0"),
  weightEnd: z
    .number()
    .optional()
    .describe("Default 1000000 (a catch-all upper bound). Same unit as your SKU weights"),
  pricePercent: z
    .number()
    .optional()
    .describe("Percentage of the order total added to shipping, e.g. 10 for 10%. Default 0"),
  pricePercentByWeight: z.number().optional().describe("Default 0"),
  maxVolume: z.number().optional().describe("cm³. Default 1000000000"),
  country: z.string().optional().describe("Three-letter ISO code. Default FRA"),
});

export function registerShippingTools(server: McpServer) {
  // ─── Shipping policies ─────────────────────────────────────────────────

  server.registerTool(
    "vtex_list_shipping_policies",
    {
      title: "List shipping policies",
      description:
        "GET /api/logistics/pvt/shipping-policies — the seller's shipping policies, as `{ items, paging }`. This is the writable surface, so an id from here is valid for vtex_update_shipping_policy.",
    },
    safeNoArgs(listShippingPolicies)
  );

  server.registerTool(
    "vtex_get_shipping_policy",
    {
      title: "Get shipping policy",
      description:
        "GET /api/logistics/pvt/shipping-policies/{id} — one policy in full: shipping method, weekend and holiday flags, max dimensions, value limits and business hours. Do NOT read carrierInfo.linkedDocks from here: VTEX returns it empty on this endpoint even when docks are linked. Use vtex_list_shipping_policies for dock links.",
      inputSchema: z.object({ id: z.string() }),
    },
    safe(({ id }) => getShippingPolicy(id))
  );

  server.registerTool(
    "vtex_create_shipping_policy",
    {
      title: "Create shipping policy",
      description:
        "POST /api/logistics/pvt/shipping-policies — creates a shipping policy. The id is chosen by the caller, not generated by VTEX. Only the fields a person decides are exposed; scheduled delivery, cubic weight, modals, business hours and pickup points are filled with the unrestricted defaults VTEX itself stores. A new policy quotes nothing until it has a dock (vtex_update_dock) and rates (vtex_set_freight_rates) — vtex_check_shipping_setup lists what is still missing.",
      inputSchema: z.object({
        id: z.string().describe('Id to assign, e.g. "2". Must not already exist.'),
        name: z.string().describe('Policy name, e.g. "Express Delivery"'),
        shippingMethod: z
          .string()
          .describe('Shipping method shown in freight simulation, e.g. "Express"'),
        isActive: z.boolean().optional().describe("Default true"),
        deliverySaturday: z.boolean().optional().describe("Default false"),
        deliverySunday: z.boolean().optional().describe("Default false"),
        deliveryHoliday: z.boolean().optional().describe("Default false"),
        numberOfItemsPerShipment: z.number().int().min(1).optional().describe("Default 1"),
        minimumValueAceptable: z.number().optional().describe("In cents. Default 0 (no minimum)"),
        maximumValueAceptable: z.number().optional().describe("In cents. Default 0 (no maximum)"),
        largestMeasure: z.number().optional().describe("Default 0 (unrestricted)"),
        maxMeasureSum: z.number().optional().describe("Default 0 (unrestricted)"),
      }),
    },
    safe(createShippingPolicy)
  );

  server.registerTool(
    "vtex_update_shipping_policy",
    {
      title: "Update shipping policy",
      description:
        "PUT /api/logistics/pvt/shipping-policies/{id} — updates a policy. Omitted fields keep their current value: the endpoint itself is a full replace that resets anything left out, so this tool reads the policy and merges your changes before sending. Returns the policy as read back afterwards.",
      inputSchema: z.object({
        id: z.string(),
        updates: z
          .object({
            name: z.string().optional(),
            shippingMethod: z.string().optional(),
            isActive: z.boolean().optional(),
            deliverySaturday: z.boolean().optional(),
            deliverySunday: z.boolean().optional(),
            deliveryHoliday: z.boolean().optional(),
            numberOfItemsPerShipment: z.number().int().min(1).optional(),
            minimumValueAceptable: z.number().optional().describe("In cents"),
            maximumValueAceptable: z.number().optional().describe("In cents"),
            largestMeasure: z.number().optional(),
            maxMeasureSum: z.number().optional(),
          })
          .describe("Only include the fields you want to change"),
      }),
    },
    safe(({ id, updates }) => updateShippingPolicy(id, updates))
  );

  // ─── Freight rates (the shipping rate table) ───────────────────────────

  server.registerTool(
    "vtex_list_freight_tables",
    {
      title: "List freight tables",
      description:
        "GET /api/logistics/pvt/configuration/freights — every shipping policy with the state of its rate table. Start here when a policy quotes no price: an empty table reports itself as freightTableValueError \"No files to proccess...\".",
    },
    safeNoArgs(listFreightTables)
  );

  server.registerTool(
    "vtex_get_freight_rates",
    {
      title: "Get freight rates for a postal code",
      description:
        "GET /api/logistics/pvt/configuration/freights/{policyId}/{postalCode}/values — the rate rows covering ONE postal code. VTEX offers no way to read a whole rate table, so this answers \"what would this address be charged\", not \"show me everything I configured\". Postal codes may be written normally; they are padded to 8 digits internally.",
      inputSchema: z.object({
        policyId: z.string().describe("Shipping policy id — VTEX calls it carrierId here"),
        postalCode: z.string().describe('e.g. "75001"'),
      }),
    },
    safe(({ policyId, postalCode }) => getFreightRates(policyId, postalCode))
  );

  server.registerTool(
    "vtex_set_freight_rates",
    {
      title: "Set freight rates",
      description:
        "POST /api/logistics/pvt/configuration/freights/{policyId}/values/update — sets the shipping prices of a policy by postal-code range. Prices are in the account currency, not cents; delivery time is in days. UPSERT, NOT REPLACE: rows you name are created or updated, rows you do not name are left untouched, and re-sending an identical row never duplicates it. A row is identified by its postal-code range plus weight range plus country, so changing a price means re-sending the same ranges with the new price. Overlapping postal-code ranges are refused before anything is sent, because VTEX accepts them and then quotes an arbitrary one of them.",
      inputSchema: z.object({
        policyId: z.string(),
        rates: z.array(freightRate).min(1),
      }),
    },
    safe(({ policyId, rates }) => setFreightRates(policyId, rates))
  );

  server.registerTool(
    "vtex_delete_freight_rates",
    {
      title: "Delete freight rates",
      description:
        "Same endpoint with operationType 3 — removes the named rate rows and leaves the rest of the table alone. The postal-code range, weight range and country must match the existing row for the delete to bite; read the row first with vtex_get_freight_rates if unsure.",
      inputSchema: z.object({
        policyId: z.string(),
        rates: z.array(freightRate).min(1),
      }),
    },
    safe(({ policyId, rates }) => deleteFreightRates(policyId, rates))
  );

  // ─── Wiring ────────────────────────────────────────────────────────────

  server.registerTool(
    "vtex_list_trade_policies",
    {
      title: "List trade policies",
      description:
        "GET /api/catalog_system/pvt/saleschannel/list — the account's trade policies (sales channels). A dock is attached to one through its salesChannels, which vtex_update_dock sets.",
    },
    safeNoArgs(listTradePolicies)
  );

  server.registerTool(
    "vtex_check_shipping_setup",
    {
      title: "Check shipping setup",
      description:
        "Walks the whole chain for one shipping policy and reports what is missing: warehouse → dock → policy → trade policy → rate table. Read-only. Use it to answer \"why does this policy not appear in shipping simulation?\" — none of those links is visible from the policy itself, which is why a policy can look configured and still never quote.",
      inputSchema: z.object({
        policyId: z.string(),
        postalCode: z
          .string()
          .optional()
          .describe(
            'Optional: also check that this address actually gets a price, e.g. "75001". Worth passing — a loaded table still quotes nothing for a postal code no row spans.'
          ),
      }),
    },
    safe(({ policyId, postalCode }) => checkShippingSetup(policyId, postalCode))
  );
}
